### ISSUE TITLE
USB Camera

### ISSUE THREAD

**Issue by TheMasterRoot** [FreakFrakFrok/Raspicam#1]
There is a way to use USB camera ?

**Comment by FreakFrakFrok** [comment]
Hi, and thanks for asking.
Well, right now all the code and testing has been done using a raspberry camera module like V1 and V2. So the answer is, right now is not possible.
https://projects.raspberrypi.org/en/projects/getting-started-with-picamera

I will look forward to do some tweaks on the code in the future as and option for anyone who wants to record via USB camera to Raspberry Pi or you are free to modify Edata_Detection.py to create 3 files: A thumbnail, a high resolution picture and a 30secs video every time that movement detection is detected. This files should be on Uploads folders to be sent to the server.
